version: '3.3'
services:
    web:
        ports:
          - '8027:8080'
        restart: always
        build:
          context: .
          dockerfile: Dockerfile
        depends_on:
          - db
        networks:
          - app-network
    db:
      image: mysql:8.0
      container_name: mysql-database
      restart: always
      ports:
       - 3306:3306
      environment:
        MYSQL_DATABASE: list_musique
        MYSQL_USER: user
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
      networks:
        - app-network
    phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 8080:80
      depends_on:
        - db
      environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
      networks:
        - app-network
volumes:
    db_vol:
networks:
  app-network:
    driver: bridge