version: '3.3'
services:
    mysql-database:
      image: mysql:8.0
      container_name: mysql-database
      restart: always
      ports:
       - "3306:3306"
      environment:
        MYSQL_DATABASE: list_musique
        MYSQL_USER: user
        MYSQL_PASSWORD: user
        MYSQL_ROOT_PASSWORD: user
        MYSQL_ROOT_HOST: '%'
      networks:
        - app-network
    phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin
      restart: always
      ports:
        - "8081:80"
      environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: user
        MYSQL_ROOT_PASSWORD: user
        MYSQL_ROOT_HOST: '%'
        PMA_HOST: mysql-database
      depends_on:
        - mysql-database
      networks:
        - app-network
    spring:
      container_name: springapp
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql/list_musique?useSSL=false&allowPublicKeyRetrieval=true
        SPRING_DATASOURCE_USERNAME: user
        SPRING_DATASOURCE_PASSWORD: user
        APP_PORT: 8080
      depends_on:
        - mysql-database
volumes:
    db_vol:
networks:
  app-network:
    name: app-network
    driver: bridge