version: '3.3'
services:
    docker-mysql:
      image: mysql:8.0
      container_name: docker-mysql
      restart: always
      ports:
       - "3306:3306"
      environment:
        MYSQL_DATABASE: list_musique
        MYSQL_USER: user
        MYSQL_PASSWORD: user
        MYSQL_ROOT_PASSWORD: user
    phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin
      restart: always
      ports:
        - "8081:80"
      environment:
        PMA_HOST: docker-mysql
      depends_on:
        - docker-mysql
    spring:
      container_name: springapp
      restart: always
      image: verkeur08/demoapp
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/list_musique?useSSL=false&allowPublicKeyRetrieval=true
        SPRING_DATASOURCE_USERNAME: user
        SPRING_DATASOURCE_PASSWORD: user
        APP_PORT: 8080
      depends_on:
        - docker-mysql
